# Generated by Django 3.2.18 on 2023-03-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_alter_rate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Fair'), (4, '4 - Good'), (5, '5 - Excellent')]),
        ),
    ]
