# Generated by Django 3.2.18 on 2023-03-02 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.TextField(blank=True, max_length=50)),
                ('location', models.TextField(blank=True, max_length=255)),
                ('location_filter', models.CharField(choices=[('temple_bar', 'Temple Bar'), ('sandymount', 'Sandymount'), ('rathmines', 'Rathmines'), ('portobello', 'Portobello'), ('ballsbridge', 'Ballsbridge'), ('dublin_docklands', 'Dublin Docklands'), ('smithfield', 'Smithfield'), ('cabra', 'Cabra'), ('ashtown', 'Ashtown'), ('phibsborough', 'Phibsboorough')], default='normal', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
