# Generated by Django 3.2.18 on 2023-03-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_alter_details_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='post',
        ),
    ]
