# Generated by Django 3.2.18 on 2023-03-04 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_remove_details_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='location_filter',
        ),
    ]
